### ISSUE TITLE
Refactor hardcoded magic numbers

### ISSUE THREAD

**Issue by tshemsedinov** [Er4ik/Web_Site_Shop#82]
For example here:

**Comment by tshemsedinov** [comment]
https://github.com/Er4ik/Web_Site_Shop/blob/476ceebdcc0f8729b97de85d8478c41f2b61ea86/js/animation.js#L134-L135

**Comment by tshemsedinov** [comment]
https://github.com/Er4ik/Web_Site_Shop/blob/476ceebdcc0f8729b97de85d8478c41f2b61ea86/js/animation.js#L473-L477

**Comment by Er4ik** [comment]
fixed
