### ISSUE TITLE
Strange antipattern

### ISSUE THREAD

**Issue by tshemsedinov** [Er4ik/Web_Site_Shop#83]
It's a vary strange crap, mutation inside expression and rewriting fields multiple times
https://github.com/Er4ik/Web_Site_Shop/blob/476ceebdcc0f8729b97de85d8478c41f2b61ea86/js/animation.js#L87-L100

**Comment by tshemsedinov** [comment]
countNum and offset will change multiple times, why?

**Comment by Er4ik** [comment]
fixed
